import "./main.css";
import Head from "next/head";

export const metadata = {
  title: "Graphoblog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/* // Remove the font link from layout.js */}
      <body>{children}</body>
    </html>
  );
}
